site_name: UnBIAS
site_description: UnBIAS Library
site_url: https://your-library-website.com
repo_url: https://github.com/VectorInstitute/NewsMediaBias
edit_uri: edit/main/docs/
site_author: Brandon Jaipersaud
copyright: Copyright © 2023 Your Organization
nav:
  - Home: index.md
  # - How UnBias Works: how_unbias_works.md
  - API Reference:
        - BiasPipeline: bias_pipeline.md
        - Core Functions: core_functions.md
        - Utility Functions: utils.md
        - Constants: constants.md



        # - run_pipeline_on_texts(): run_pipeline_on_texts.md
        # - get_debiased_sequence(): run_pipeline_on_texts.md
   
        # - re_incomplete_sentence(): re_incomplete_sentence.md
        # - tokenize_for_prediction(): tokenize_for_prediction.md
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details



