site_name: UnBIAS
site_description: UnBIAS Library
site_url: https://your-library-website.com
repo_url: https://github.com/yourusername/my-library
edit_uri: edit/main/docs/
site_author: Brandon Jaipersaud
copyright: Copyright © 2023 Your Organization
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference:
    - Module 1: module1.md
    - Module 2: module2.md
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



